ALIVE_Core_JSON = require("ALIVE_Core_JSON.lua");

ALIVE_FileUtils_CurrentlyActiveSaveIndex = 1;
ALIVE_FileUitls_SubDirectory = "AliveInside\\"
ALIVE_FileUtils_SavesDirectory = ALIVE_FileUitls_SubDirectory .. "Saves\\"

ALIVE_FileUtils_ActiveSave = nil;
ALIVE_FileUtils_OptionsFile = nil;

ALIVE_FileUtils_IsCurrentlyInitialized = false;

--Decodes a JSON file and returns the raw object. Useful for non-standard reads.
ALIVE_Core_FileUtils_DecodeJSONFile = function(fileName) 
    local theFile = (io.open)(fileName, "r") --Open the file
    if theFile == nil then
        return nil;
    end

    local content = theFile:read("*all") --Read the file's content
    theFile:close()
    
    return ALIVE_Core_JSON.decode(content) --Return the decoded file.
end

ALIVE_Core_FileUtils_SaveSetCheckpoint = function(checkpoint)
    if ALIVE_FileUtils_OptionsFile == nil or ALIVE_FileUtils_ActiveSave == nil then
        return false;
    end
    
    ALIVE_FileUtils_ActiveSave.checkpoint = checkpoint;
    local saveFile = (io.open)(ALIVE_FileUtils_SavesDirectory.."AliveInside-Save"..ALIVE_FileUtils_OptionsFile.activeSaveFile..".json", "w")
    saveFile:write(ALIVE_Core_JSON.encode(ALIVE_FileUtils_ActiveSave));
    saveFile:close();    

    return true;
end

ALIVE_Core_FileUtils_Init = function()
    if not ALIVE_Core_FileUtils_DirectoryExists(ALIVE_FileUitls_SubDirectory) then --Create File Tree
        print("Alive Inside SubDirectory Not Found! Creating...");
        os.execute("mkdir ".. ALIVE_FileUtils_SavesDirectory);  
    end

    if not ALIVE_Core_FileUtils_FileExists(ALIVE_FileUitls_SubDirectory.."options.json") then
        print("Options file not found! Creating...")
        local gameOptions = (io.open)(ALIVE_FileUitls_SubDirectory.."options.json", "w");
        gameOptions:write(ALIVE_FileUtils_GenericOptionsFile);
        gameOptions:close();
    end

    ALIVE_FileUtils_OptionsFile = ALIVE_Core_FileUtils_DecodeJSONFile(ALIVE_FileUitls_SubDirectory.."options.json");

    if not ALIVE_Core_FileUtils_FileExists(ALIVE_FileUtils_SavesDirectory.."AliveInside-Save"..ALIVE_FileUtils_OptionsFile.activeSaveFile..".json") then
        print("Save file not found! Creating...")
        local saveFile = (io.open)(ALIVE_FileUtils_SavesDirectory.."AliveInside-Save"..ALIVE_FileUtils_OptionsFile.activeSaveFile..".json", "w")
        saveFile:write(ALIVE_FileUtils_GenericSaveFile);
        saveFile:close();
    end

    ALIVE_FileUtils_ActiveSave = ALIVE_Core_FileUtils_DecodeJSONFile(ALIVE_FileUtils_SavesDirectory.."AliveInside-Save"..ALIVE_FileUtils_OptionsFile.activeSaveFile..".json");

    ALIVE_FileUtils_IsCurrentlyInitialized = true;
    print("FileUtils Initialization Complete.") --We now have all requisite files and are ready to use them.
end

ALIVE_Core_FileUtils_FileExists = function(file)
   local ok, err, code = os.rename(file, file)
   if not ok then
      if code == 13 then
         -- Permission denied, but it exists
         return true
      end
   end
   return ok, err
end

ALIVE_Core_FileUtils_DirectoryExists = function(directory)
    return ALIVE_Core_FileUtils_FileExists(directory)
end

ALIVE_FileUtils_GenericOptionsFile = [[
{
  "warning": "Hello there! This file was automatically generated by Alive Inside. It's not recommended to modify it yourself!",
  "activeSaveFile": 1,
  "screenReaderCompat": false
}
]]

--[[
Save File Checkpoint Definitions:

0 - Not Yet Started
1 - Intro, Configurator Complete.
2 - Infinite Runner
3 - Infinite Runner End, School Reunion & Defense 
4 - School Hub
5 - Scavenging - Group 1 - Beach
6 - Scavenging - Group 2 - Greenhouse / Admin
7 - Finale
99 - Fully Completed.

--]]

ALIVE_FileUtils_GenericSaveFile = [[
{
  "configurator": {
    "s2KilledKenny": false,
    "s2Wellington": false,
    "s2Alone": false,
    "s4KilledLilly": false,
    "s4SavedViolet": false,
    "s4TrustedAJ": false
  },
  "checkpoint": 0
}
]]

if ALIVE_Core_Project_IsDebugMode then
    ALIVE_FileUtils_GenericSaveFile = [[
    {
        "configurator": {
        "s2KilledKenny": false,
        "s2Wellington": false,
        "s2Alone": false,
        "s4KilledLilly": true,
        "s4SavedViolet": true,
        "s4TrustedAJ": false
        },
        "checkpoint": 1
    }
]]
end