ALIVE_Scene_LevelCleanup_403_TrainTile = function(kScene)
    --local test1 = AgentCreate("zombs", "sk61_zombie400.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);
    --local test1 = AgentCreate("zombs", "zombie.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);
    --local test1 = AgentCreate("zombs", "sk61_zombie400Sherak.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);
    --ALIVE_AgentSetProperty("zombs", "Runtime: Visible", true, kScene);

    ALIVE_RemovingAgentsWithPrefix(kScene, "light_CHAR_CC");
    ALIVE_RemovingAgentsWithPrefix(kScene, "lightrig");
    ALIVE_RemovingAgentsWithPrefix(kScene, "audio_");
    ALIVE_RemovingAgentsWithPrefix(kScene, "fx_");
    ALIVE_RemovingAgentsWithPrefix(kScene, "fxg_");
    ALIVE_RemovingAgentsWithPrefix(kScene, "fxa_");
    ALIVE_RemovingAgentsWithPrefix(kScene, "obj_lookAt");
    
    --ALIVE_SetPropertyOnAgentsWithPrefix(kScene, "Zombie", "Runtime: Visible", true)
    --ALIVE_SetPropertyOnAgentsWithPrefix(kScene, "Zombie", "Runtime: Visible", false)

    ALIVE_SetPropertyOnAgentsWithPrefix(kScene, "adv_", "Render Static", false)

    --ALIVE_SetPropertyOnAgentsWithPrefix(kScene, "adv_", "Runtime: Visible", true)
    --ALIVE_SetPropertyOnAgentsWithPrefix(kScene, "obj_", "Runtime: Visible", true)
    --ALIVE_RemovingAgentsWithPrefix(kScene, "Zombie");
    
    --ALIVE_AgentSetProperty("group_tile1", "Group - Visible", false, kScene);

    ALIVE_AgentSetProperty("Clementine", "Runtime: Visible", true, kScene);
    ALIVE_AgentSetProperty("AJ", "Runtime: Visible", true, kScene);

    ALIVE_RemoveAgent("module_post_effect", kScene);
    ALIVE_RemoveAgent("Lee", kScene);
    ALIVE_RemoveAgent("ClementineFlashback", kScene);
    --ALIVE_RemoveAgent("Clementine", kScene);
    --ALIVE_RemoveAgent("AJ", kScene);
    ALIVE_RemoveAgent("light_ENV_roadTile", kScene);
    --ALIVE_RemoveAgent("light_SKY_amb", kScene);
    ALIVE_RemoveAgent("light_SKY_horizonSpot", kScene);
    ALIVE_RemoveAgent("light_SKY_sunPoint", kScene);
    ALIVE_RemoveAgent("light_SKY_sunBroadLight", kScene);
    ALIVE_RemoveAgent("light_ENV_ambFill", kScene);
    --ALIVE_RemoveAgent("light_ENV_D_SunKey", kScene);
    ALIVE_RemoveAgent("light_AMB_grassIvy", kScene);
    ALIVE_RemoveAgent("light_AMB_MatteTrees", kScene);
    ALIVE_RemoveAgent("light_NODE_roadTile", kScene);
    ALIVE_RemoveAgent("module_post_effect", kScene);
    --ALIVE_RemoveAgent("module_environment", kScene);
    ALIVE_RemoveAgent("obj_matteForestTileRing", kScene);
    --ALIVE_RemoveAgent("obj_skydomeOverheadClouds", kScene);
    ALIVE_RemoveAgent("obj_trainEngineFlashbackInnerWalls", kScene);
    ALIVE_RemoveAgent("obj_trainEngineFlashbackJunk", kScene);
    ALIVE_RemoveAgent("obj_trainEngineFlashbackOuterWalls", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClem", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemFurniture", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemCloth", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemCobwebs", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemPipes", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemCeiling", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemFloor", kScene);
    ALIVE_RemoveAgent("obj_doorClemBoardingSchoolDorm", kScene);
    ALIVE_RemoveAgent("obj_doorClosetClemABoardingSchoolDorm", kScene);
    ALIVE_RemoveAgent("obj_drawingAJ", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAWalls", kScene);
    ALIVE_RemoveAgent("obj_drawerBoardingSchoolDorm", kScene);
    ALIVE_RemoveAgent("obj_drawerDeskABoardingSchoolDorm", kScene);
    ALIVE_RemoveAgent("obj_pillowDormA", kScene);
    ALIVE_RemoveAgent("obj_capClementine400", kScene);
    ALIVE_RemoveAgent("obj_trainBoxCar", kScene);
    ALIVE_RemoveAgent("obj_trainCoalCar", kScene);
    ALIVE_RemoveAgent("obj_trainCoalCar01", kScene);
    ALIVE_RemoveAgent("obj_trainBoxCar01", kScene);
    ALIVE_RemoveAgent("light_NODE_clemsRoomNight", kScene);
    ALIVE_RemoveAgent("light_ENV_clemsRoomNight_moonKey", kScene);
    ALIVE_RemoveAgent("light_ENV_clemsRoomNight_moonHotspot", kScene);
    ALIVE_RemoveAgent("light_ENV_clemsRoomNight_moonBounceDoor", kScene);
    ALIVE_RemoveAgent("light_ENV_clemsRoomNight_moonBounceWindow", kScene);
    ALIVE_RemoveAgent("light_ENV_clemsRoomNight", kScene);
    ALIVE_RemoveAgent("light_ENV_clemsRoomNight_moonBounceWindow01", kScene);
    ALIVE_RemoveAgent("fx_lightShaft402", kScene);
    ALIVE_RemoveAgent("light_SKY_ambRoomB", kScene);
    ALIVE_RemoveAgent("light_SKY_horizonSpotRoomB", kScene);
    ALIVE_RemoveAgent("obj_skydomeStars", kScene);
    ALIVE_RemoveAgent("obj_skydomeOverheadCloudsRoomB", kScene);
    ALIVE_RemoveAgent("obj_skydomeMoonRoomB", kScene);
    ALIVE_RemoveAgent("obj_matteForestTileRingRoomB", kScene);
    ALIVE_RemoveAgent("light_NODE_roadTileKey", kScene);
    ALIVE_RemoveAgent("light_ENV_P_leeSpecial01", kScene);
    ALIVE_RemoveAgent("light_ENV_P_leeSpecial02", kScene);
    ALIVE_RemoveAgent("light_AMB_Trees01", kScene);
    ALIVE_RemoveAgent("fx_forceBackBufferStaticObj", kScene);
    
    ALIVE_RemoveAgent("groupA", kScene);
    ALIVE_RemoveAgent("groupB", kScene);
    ALIVE_RemoveAgent("groupC", kScene);
    ALIVE_RemoveAgent("groupD", kScene);
    ALIVE_RemoveAgent("groupE", kScene);
    ALIVE_RemoveAgent("groupF", kScene);
    ALIVE_RemoveAgent("groupG", kScene);
    ALIVE_RemoveAgent("group_tileParent", kScene);
    ALIVE_RemoveAgent("group_tileGrandParent", kScene);
    ALIVE_RemoveAgent("group_dormRoom", kScene);
    ALIVE_RemoveAgent("group_train", kScene);
    ALIVE_RemoveAgent("group_skydomeRoomB", kScene);
    ALIVE_RemoveAgent("group_moonRoomB", kScene);

    local envGroupPartA = AgentCreate("MainEnvGroup_PartA", "group.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);
    local envGroupPartB = AgentCreate("MainEnvGroup_PartB", "group.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);
    local envGroupPartC = AgentCreate("MainEnvGroup_PartC", "group.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);
    local envGroupPartD = AgentCreate("MainEnvGroup_PartD", "group.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);
    local envGroupPartE = AgentCreate("MainEnvGroup_PartE", "group.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);
    local envGroupPartF = AgentCreate("MainEnvGroup_PartF", "group.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);
    local envGroupPartG = AgentCreate("MainEnvGroup_PartG", "group.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);

    --local regularSceneAgent = AgentFindInScene("adv_roadTile_meshesCTerrainA", kScene);
    --local regularSceneAgentProperties = AgentGetRuntimeProperties(regularSceneAgent);
    --local sceneRenderLightingGroup = PropertyGet(regularSceneAgentProperties, "Render Lighting Groups");

    --ALIVE_AgentSetProperty("fafsafsafsafsaf", "Render Lighting Groups", sceneRenderLightingGroup, kScene);

    --------------------------------- PART A ---------------------------------
    --------------------------------- PART A ---------------------------------
    --------------------------------- PART A ---------------------------------
    AgentAttach(AgentFindInScene("adv_roadTile_meshesACarA", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesAFencesPowerLinesA", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesAFencesPowerLinesB", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesAFencesPowerLinesD", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesAGrassA", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesAGrassB", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesAGrassC", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesAGrassD", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesARocksA", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesARocksB", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesARocksC", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesARocksD", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATerrainA", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATerrainB", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATerrainC", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATerrainD", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATreeFlatsA", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATreeFlatsB", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATreeFlatsC", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATreeFlatsD", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATreesA", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATreesB", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATreesC", kScene), envGroupPartA);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesATreesD", kScene), envGroupPartA);

    ALIVE_RemoveAgent("adv_roadTile_meshesACarA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesAFencesPowerLinesA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesAFencesPowerLinesB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesAFencesPowerLinesD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesAGrassA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesAGrassB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesAGrassC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesAGrassD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesARocksA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesARocksB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesARocksC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesARocksD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATerrainA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATerrainB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATerrainC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATerrainD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATreeFlatsA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATreeFlatsB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATreeFlatsC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATreeFlatsD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATreesA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATreesB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATreesC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesATreesD", kScene);
    --------------------------------- PART B ---------------------------------
    --------------------------------- PART B ---------------------------------
    --------------------------------- PART B ---------------------------------
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBGrassA", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBGrassB", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBGrassC", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBGrassD", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBHouse", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBPuddles", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBRocksA", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBRocksB", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBRocksC", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBRocksD", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTerrainA", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTerrainB", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTerrainC", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTerrainD", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTreeFlatsA", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTreeFlatsB", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTreeFlatsC", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTreeFlatsD", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTreesA", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTreesB", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTreesC", kScene), envGroupPartB);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesBTreesD", kScene), envGroupPartB);

    ALIVE_RemoveAgent("adv_roadTile_meshesBGrassA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBGrassB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBGrassC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBGrassD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBHouse", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBPuddles", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBRocksA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBRocksB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBRocksC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBRocksD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTerrainA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTerrainB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTerrainC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTerrainD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTreeFlatsA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTreeFlatsB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTreeFlatsC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTreeFlatsD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTreesA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTreesB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTreesC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesBTreesD", kScene);
    --------------------------------- PART C ---------------------------------
    --------------------------------- PART C ---------------------------------
    --------------------------------- PART C ---------------------------------
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCBushesA", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCBushesB", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCGrassA", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCGrassB", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCGrassC", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCGrassD", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCGrassOpening", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCRocksA", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCRocksB", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCRocksC", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCRocksD", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCSignsA", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTerrainA", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTerrainB", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTerrainC", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTerrainD", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTreeFlatsA", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTreeFlatsB", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTreeFlatsC", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTreeFlatsD", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTreesA", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTreesB", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTreesC", kScene), envGroupPartC);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesCTreesD", kScene), envGroupPartC);

    --ALIVE_AgentSetProperty("adv_roadTile_meshesCBushesA", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCBushesB", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCGrassA", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCGrassB", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCGrassC", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCGrassD", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCGrassOpening", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCTreeFlatsA", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCTreeFlatsB", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCTreeFlatsC", "Render Lighting Groups", sceneRenderLightingGroup, kScene);
    --ALIVE_AgentSetProperty("adv_roadTile_meshesCTreeFlatsD", "Render Lighting Groups", sceneRenderLightingGroup, kScene);

    --ALIVE_RemoveAgent("adv_roadTile_meshesCBushesA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCBushesB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCGrassA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCGrassB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCGrassC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCGrassD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCGrassOpening", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCRocksA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCRocksB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCRocksC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCRocksD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCSignsA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTerrainA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTerrainB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTerrainC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTerrainD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTreeFlatsA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTreeFlatsB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTreeFlatsC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTreeFlatsD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTreesA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTreesB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTreesC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesCTreesD", kScene);
    --------------------------------- PART D ---------------------------------
    --------------------------------- PART D ---------------------------------
    --------------------------------- PART D ---------------------------------
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDFencesB", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDFencesD", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDGrassA", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDGrassB", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDGrassC", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDGrassD", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDHouse", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDRocksA", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDRocksB", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDRocksC", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDRocksD", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDSignsA", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTerrainA", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTerrainB", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTerrainC", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTerrainD", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreeFlatsA", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreeFlatsB", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreeFlatsC", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreeFlatsD", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreesA", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreesB", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreesC", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreesD", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreesE", kScene), envGroupPartD);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesDTreesF", kScene), envGroupPartD);

    --[[
    --local partD_pos = Vector(0, 25, 0);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDFencesB", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDFencesD", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDGrassA", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDGrassB", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDGrassC", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDGrassD", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDHouse", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDRocksA", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDRocksB", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDRocksC", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDRocksD", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDSignsA", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTerrainA", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTerrainB", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTerrainC", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTerrainD", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreeFlatsA", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreeFlatsB", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreeFlatsC", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreeFlatsD", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreesA", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreesB", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreesC", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreesD", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreesE", partD_pos, kScene);
    ALIVE_SetAgentWorldPosition("adv_roadTile_meshesDTreesF", partD_pos, kScene);
    ]]--

    ALIVE_RemoveAgent("adv_roadTile_meshesDFencesB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDFencesD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDGrassA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDGrassB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDGrassC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDGrassD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDHouse", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDRocksA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDRocksB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDRocksC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDRocksD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDSignsA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTerrainA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTerrainB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTerrainC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTerrainD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDTreeFlatsA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDTreeFlatsB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDTreeFlatsC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesDTreeFlatsD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTreesA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTreesB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTreesC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTreesD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTreesE", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesDTreesF", kScene);
    --------------------------------- PART E ---------------------------------
    --------------------------------- PART E ---------------------------------
    --------------------------------- PART E ---------------------------------
    AgentAttach(AgentFindInScene("adv_roadTile_meshesEFencesPowerLinesA", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesEFencesPowerLinesC", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesEFencesPowerLinesD", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesEGrassA", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesEGrassB", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesEGrassC", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesEGrassD", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesEHouse", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesERocksA", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesERocksB", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesERocksC", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesERocksD", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETerrainA", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETerrainB", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETerrainC", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETerrainD", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreeFlatsA", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreeFlatsB", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreeFlatsC", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreeFlatsD", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreesA", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreesB", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreesC", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreesD", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreesE", kScene), envGroupPartE);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesETreesF", kScene), envGroupPartE);

    --ALIVE_RemoveAgent("adv_roadTile_meshesEFencesPowerLinesA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesEFencesPowerLinesC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesEFencesPowerLinesD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesEGrassA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesEGrassB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesEGrassC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesEGrassD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesEHouse", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesERocksA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesERocksB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesERocksC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesERocksD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETerrainA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETerrainB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETerrainC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETerrainD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesETreeFlatsA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesETreeFlatsB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesETreeFlatsC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesETreeFlatsD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETreesA", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETreesB", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETreesC", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETreesD", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETreesE", kScene);
    --ALIVE_RemoveAgent("adv_roadTile_meshesETreesF", kScene);
    --------------------------------- PART F ---------------------------------
    --------------------------------- PART F ---------------------------------
    --------------------------------- PART F ---------------------------------
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFBushesA", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFBushesB", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFBushesD", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFBushesE", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFBushesF", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFFencesSignsA", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFFencesSignsB", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFFencesSignsC", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFFencesSignsE", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFFencesSignsF", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFGrassA", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFGrassB", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFGrassC", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFGrassD", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFGrassE", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFGrassF", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFHouse", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFRocksA", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFRocksB", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFRocksC", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFRocksD", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFRocksE", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFRocksF", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTerrainA", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTerrainB", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTerrainC", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTerrainD", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTerrainE", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTerrainF", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreeFlatsA", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreeFlatsB", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreeFlatsC", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreeFlatsD", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreeFlatsE", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreeFlatsF", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreesA", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreesB", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreesC", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreesD", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreesE", kScene), envGroupPartF);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesFTreesF", kScene), envGroupPartF);

    ALIVE_RemoveAgent("adv_roadTile_meshesFBushesA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFBushesB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFBushesD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFBushesE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFBushesF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFFencesSignsA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFFencesSignsB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFFencesSignsC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFFencesSignsE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFFencesSignsF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFGrassA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFGrassB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFGrassC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFGrassD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFGrassE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFGrassF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFHouse", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFRocksA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFRocksB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFRocksC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFRocksD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFRocksE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFRocksF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTerrainA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTerrainB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTerrainC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTerrainD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTerrainE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTerrainF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreeFlatsA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreeFlatsB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreeFlatsC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreeFlatsD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreeFlatsE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreeFlatsF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreesA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreesB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreesC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreesD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreesE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesFTreesF", kScene);
    --------------------------------- PART G ---------------------------------
    --------------------------------- PART G ---------------------------------
    --------------------------------- PART G ---------------------------------
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGBushesA", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGBushesB", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGBushesD", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGBushesE", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGBushesF", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGFencesSignsA", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGFencesSignsB", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGFencesSignsD", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGFencesSignsE", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGFencesSignsF", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGGrassA", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGGrassB", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGGrassC", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGGrassD", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGGrassE", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGGrassF", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGRocksA", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGRocksB", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGRocksC", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGRocksD", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGRocksE", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGRocksF", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTerrainA", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTerrainB", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTerrainC", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTerrainD", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTerrainE", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTerrainF", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreeFlatsA", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreeFlatsB", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreeFlatsC", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreeFlatsD", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreeFlatsE", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreeFlatsF", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreesA", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreesB", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreesC", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreesD", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreesE", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreesE", kScene), envGroupPartG);
    AgentAttach(AgentFindInScene("adv_roadTile_meshesGTreesF", kScene), envGroupPartG);

    ALIVE_RemoveAgent("adv_roadTile_meshesGBushesA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGBushesB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGBushesD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGBushesE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGBushesF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGFencesSignsA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGFencesSignsB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGFencesSignsD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGFencesSignsE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGFencesSignsF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGGrassA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGGrassB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGGrassC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGGrassD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGGrassE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGGrassF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGRocksA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGRocksB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGRocksC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGRocksD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGRocksE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGRocksF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTerrainA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTerrainB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTerrainC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTerrainD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTerrainE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTerrainF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreeFlatsA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreeFlatsB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreeFlatsC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreeFlatsD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreeFlatsE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreeFlatsF", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreesA", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreesB", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreesC", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreesD", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreesE", kScene);
    ALIVE_RemoveAgent("adv_roadTile_meshesGTreesF", kScene);

    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClem", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemFurniture", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemCloth", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemCobwebs", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemPipes", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemCeiling", kScene);
    ALIVE_RemoveAgent("adv_boardingSchoolDorm_meshesAClemFloor", kScene);



    --ALIVE_SetAgentWorldPosition("MainEnvGroup_PartA", Vector(0, 0, 0), kScene);
    --ALIVE_SetAgentWorldPosition("MainEnvGroup_PartB", Vector(0, 0, 0), kScene);
    --ALIVE_SetAgentWorldPosition("MainEnvGroup_PartC", Vector(0, 0, 0), kScene);
    --ALIVE_SetAgentWorldPosition("MainEnvGroup_PartD", Vector(0, 25, 0), kScene);
    --ALIVE_SetAgentWorldPosition("MainEnvGroup_PartE", Vector(0, 0, 0), kScene);
    --ALIVE_SetAgentWorldPosition("MainEnvGroup_PartF", Vector(0, 0, 0), kScene);
    --ALIVE_SetAgentWorldPosition("MainEnvGroup_PartG", Vector(0, 0, 0), kScene);

    --AgentSetPos(envGroupPartD, Vector(0, 25, 0));

    --local envGroup = AgentCreate("MainEnvGroup", "group.prop", Vector(0,0,0), Vector(0,0,0), kScene, false, false);

    --AgentAttach(AgentFindInScene("", kScene), envGroup);
end